Increase Chinese translation.
Tampermonkey/tampermonkey-i18n pull request #181
Opened 2021-03-26 23:46 UTC by Vstory

2021-03-27 00:34 UTC, xiaopangju requested changes
我发现有一个字符串叫做 `Add_to_icon_badge_text` ，似乎您还没有翻译，请问您能帮忙补全吗？谢谢！

2021-03-27 01:05 UTC, Vstory commented
> 我发现有一个字符串叫做 `Add_to_icon_badge_text` ，似乎您还没有翻译，请问您能帮忙补全吗？谢谢！

刚开始我下载了英文版和中文的 `messages.json` 准备比较一下，用的 EmEditor 显示结果错乱，我就直接对照实际使用中出现的文本来翻译的。

`Add_to_icon_badge_text` 添加到图标徽章文字

![Snipaste_设置 - Google Chrome_2021-03-27_09-04-13](https://user-images.githubusercontent.com/20795557/112705860-8a0caa80-8edb-11eb-8609-ef92adb97417.png)

2021-03-27 01:06 UTC, xiaopangju commented
我这边是没有什么问题的，你可以试试用其他的软件查看，例如vscode之类

2021-03-27 01:17 UTC, xiaopangju commented on zh_CN/messages.json
> +        "message": "用户脚本使用 @run-at context-menu"
你觉得这里是用“使用 @run-at 上下文菜单的用户脚本”还是“用户脚本使用 @run-at context-menu”这个译文比较好？我个人偏向前者。

2021-03-27 01:41 UTC, Vstory commented on zh_CN/messages.json
> +        "message": "用户脚本使用 @run-at context-menu"
按你的意思直接改 ;)

2021-03-27 02:48 UTC, xiaopangju commented on zh_CN/messages.json
> +        "message": "用户脚本使用 @run-at context-menu"
但是这需要你自己改，我并没有你repo的访问权限

2021-03-27 03:09 UTC, Vstory commented on zh_CN/messages.json
> +        "message": "用户脚本使用 @run-at context-menu"
不好意思，之前其他项目提交也出现过 `reviewed` ，我以为发起者可以改的。

2021-03-27 03:38 UTC, xiaopangju approved these changes

2021-03-27 03:39 UTC, xiaopangju commented
好了

2021-03-27 04:26 UTC, xiaopangju commented on zh_CN/messages.json
> +        "message": "使用 @run-at 上下文菜单的用户脚本"
你说的你以为发起者可以改可能是因为用了像下面一样的 request change
```suggestion
        "message": "使用 @run-at 上下文菜单的用户脚本"
```

2021-03-27 04:26 UTC, xiaopangju commented on zh_CN/messages.json
> +        "message": "使用 @run-at 上下文菜单的用户脚本"
不过没有什么大问题，等着被merge就可以了

2021-03-27 04:39 UTC, Vstory commented on zh_CN/messages.json
> +        "message": "使用 @run-at 上下文菜单的用户脚本"
😉

2021-03-27 23:52 UTC, xiaopangju approved these changes

2021-03-30 18:29 UTC, derjanb commented
Thank you!

2021-03-30 18:29 UTC, merged