Update Chinese Simplified Translate
Tampermonkey/tampermonkey-i18n pull request #183
Opened 2021-03-27 02:10 UTC by CaveNightingale

"function" is officially translated as "方法" when it means a method in an object (or a class).
"closing bracket" here means the bracket that matches the current one so it should be translated as "配对括号" instead of "关闭括号" which means "close the bracket".
"debug script" should be "调试脚本". The current one has wrong word order. 
Add extra information to "Line_Case_Insensitive" and "Lines" to help users understand.
"move line down" should be "下移行". The current one has wrong word order. 
"move line up" should be "上移行". The current one has wrong word order.
"save to disk" is not modified. Actually the function of this button is to save the script to local file system instead of disk. However the English translation said "disk".
"scope" is officially translated as "块" when it means the texts between "{" and "}".
"select between brackets" is changed to "选择前后括号中间的部分" because the current one "选择括号间" is strange.
"selection" should be "选择" instead of "选择内容" which means "select content".
"toggle" here means to add or remove something, not to switch.
"incremental" means "增量" instead of "增亮".

2021-03-27 03:38 UTC, xiaopangju approved these changes

2021-03-27 11:39 UTC, xiaopangju requested changes
似乎每个 `"message"` 的前面都比原来多了一个空格，你能删掉多余的一个空格吗？

2021-03-27 12:19 UTC, CaveNightingale commented
> 似乎每个 `"message"` 的前面都比原来多了一个空格，你能删掉多余的一个空格吗？

没发现哪里有问题啊，我这里看到修改前后都是每个"message"前面8个空格
并且其他语言的message.json也都是这个格式

2021-03-27 22:35 UTC, xiaopangju commented
那可能是githubapp的问题，请忽略这条review吧

Yours faithfully,

Haoran Du


________________________________
From: CaveNightingale ***@***.***>
Sent: Saturday, March 27, 2021 8:19:48 PM
To: Tampermonkey/tampermonkey-i18n ***@***.***>
Cc: Haoran Du ***@***.***>; Comment ***@***.***>
Subject: Re: [Tampermonkey/tampermonkey-i18n] Update Chinese Simplified Translate (#183)


似乎每个 "message" 的前面都比原来多了一个空格，你能删掉多余的一个空格吗？

没发现哪里有问题啊，我这里看到修改前后都是每个"message"前面8个空格
并且其他语言的message.json也都是这个格式

―
You are receiving this because you commented.
Reply to this email directly, view it on GitHub<https://github.com/Tampermonkey/tampermonkey-i18n/pull/183#issuecomment-808724169>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/ANSTLMY2AMEFZ5PMDUOWJN3TFXEOJANCNFSM4Z4MQHQQ>.

2021-03-27 23:51 UTC, xiaopangju approved these changes

2021-03-29 10:36 UTC, xiaopangju commented
哇

Yours faithfully,

Haoran Du


________________________________
From: 御坂 美琴 ***@***.***>
Sent: Sunday, March 28, 2021 6:35:29 AM
To: Tampermonkey/tampermonkey-i18n ***@***.***>; Tampermonkey/tampermonkey-i18n ***@***.***>
Cc: Comment ***@***.***>
Subject: Re: [Tampermonkey/tampermonkey-i18n] Update Chinese Simplified Translate (#183)

那可能是githubapp的问题，请忽略这条review吧

Yours faithfully,

Haoran Du


________________________________
From: CaveNightingale ***@***.***>
Sent: Saturday, March 27, 2021 8:19:48 PM
To: Tampermonkey/tampermonkey-i18n ***@***.***>
Cc: Haoran Du ***@***.***>; Comment ***@***.***>
Subject: Re: [Tampermonkey/tampermonkey-i18n] Update Chinese Simplified Translate (#183)


似乎每个 "message" 的前面都比原来多了一个空格，你能删掉多余的一个空格吗？

没发现哪里有问题啊，我这里看到修改前后都是每个"message"前面8个空格
并且其他语言的message.json也都是这个格式

―
You are receiving this because you commented.
Reply to this email directly, view it on GitHub<https://github.com/Tampermonkey/tampermonkey-i18n/pull/183#issuecomment-808724169>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/ANSTLMY2AMEFZ5PMDUOWJN3TFXEOJANCNFSM4Z4MQHQQ>.

2021-03-30 18:32 UTC, derjanb commented
Thanks!

2021-03-30 18:32 UTC, merged